### ISSUE TITLE
Font Not Defined Error in NDOT

### ISSUE THREAD

**Issue by mgallagher01** [SRF-Consulting-Group-Inc/iris#11]
After upgrading to IRIS 5.x some signs (D5-80-17 E for example) return a "FontNotDefined" error when posting messages

See if the server query overnight cleans up this error on June 30 2021.  Otherwise investigate further.

**Comment by mgallagher01** [comment]
This appears to be related to heterogeneous font tables installed on signs and IRIS's need to define a font for the sign to render it properly.
NDOT's direction is to develop a uniform font table for the signs that has one (1) font for the DMS (conforms to min character height for freeeway speeds) and one (1) font for PDMS.

This is somewhat complicated by the different resolution signs in use for DMS and possibly different (character vs matrix) signs for PDMS.

**Comment by jlstanley-git** [comment]
Consider 14" minimum character height.
