### ISSUE TITLE
Notify Caleb B (NDOT) that renaming tool is available

### ISSUE THREAD

**Issue by mgallagher01** [SRF-Consulting-Group-Inc/iris#12]
Send note to Caleb with some instructions and strongly worded cautions on its use.

**Comment by gordonparikh** [comment]
Renamer installed on ndotiris01 here: /home/srfuser/iris_renamer_v0.5/iris_renamer_v0.5.py

Configured to connect to ndotiris01 database and ready for use.

**Comment by jlstanley-git** [comment]
Since Gordon passed the basic instruction to the main NDOT crew, I'm closing this.
