### ISSUE TITLE
"STANDBY_DOTS" signs appear as "Deployed" should be "Available"

### ISSUE THREAD

**Issue by mgallagher01** [SRF-Consulting-Group-Inc/iris#14]
I think we had a mechanism to keep signs with this message in the "available" group.  Possibly a System Property.

**Comment by mgallagher01** [comment]
Check to see if the old hack is still in the "old" IRIS code in GitHub

**Comment by jlstanley-git** [comment]
BTW:  The current patch just uses the [standby] tag somewhere in the MULTI string.  It does not have the hook that uses the quick_message name prefix "standby_" to force the message to be a standby message,  I'll add that patch Monday.

**Comment by mgallagher01** [comment]
Deployed updated code to NDOT.  Just need to get this in MnDOT Mainline now.

**Comment by jlstanley-git** [comment]
Addition of the [standby] tag was accepted into MNDOT mainline.  Closed.
