### ISSUE TITLE
NDOTIRIS02 Warm Standby/Other OCIO Cleanup

### ISSUE THREAD

**Issue by gordonparikh** [SRF-Consulting-Group-Inc/iris#30]
Set up warm standby (NDOTIRIS02) by duplicating NDOTIRIS01, changing hostname, disabling comm_links. Also should install security updates on NDOTIRIS01 too.

Set up database backup pipeline (NFS for sharing backups among servers).

Ensure all 3 servers registered with RedHat (NDOTIRIS03 currently not registered, IRIS01 likely needs to be de-registered before image duplicated to IRIS02).

Semi-related: open NDOTIRIS03 port 3000 to VPN for Grafana dashboard.

**Comment by gordonparikh** [comment]
NDOTIRIS03 registered with Red Hat September 30, 2021.

**Comment by mgallagher01** [comment]
Need to get DB copy from IRIS01 to IRIS02 enabled

**Comment by mgallagher01** [comment]
I think Gordon has this done now.  If so, we can close this issue.

**Comment by gordonparikh** [comment]
Implemented [warm standby](https://github.com/SRF-Consulting-Group-Inc/iris_extras/blob/main/warmStandby.sh) in [iris_extras repository](https://github.com/SRF-Consulting-Group-Inc/iris_extras) and [documented there](https://github.com/SRF-Consulting-Group-Inc/iris_extras/wiki/IRIS-Warm-Standby-System) (note: access to that repository is currently private to our organization).
