### ISSUE TITLE
Simplify reconfiguring IRIS for developer workstations

### ISSUE THREAD

**Issue by jlstanley-git** [SRF-Consulting-Group-Inc/iris#36]
There are roughly 23 strings that are embedded in IRIS source or in two different properties files, that can be changed to support running IRIS server and client in a developer environment.  It's a tedious task to keep those strings set to the correct values for a given development environment while being careful to not accidently push or overwrite those changes when interacting with Github.  It would save time and avoid accidents if we had an optional developer.properties configuration file that would allow overriding those strings without having to modify IRIS source or the standard client/server properties files.

**Comment by gordonparikh** [comment]
I do something similar with untracked files in my local repository. Having a developer file that we sync though is a good idea.

**Comment by jlstanley-git** [comment]
Actually, the idea is the developer.properties file (with all values commented out) would be pulled from the repo when it's cloned. 
(Or possibly distributed via some separate channel.)  It would be added to the local ignore list and then customized for the developer's workstation.  So we would not be syncing the developer file.

**Comment by jlstanley-git** [comment]
In a sense, it's trying to add the troublesome strings to the Git ignore list without actually ignoring any of the mainstream IRIS code.

**Comment by mgallagher01** [comment]
Patches submitted.  Waiting for Doug to approve & merge.

**Comment by jlstanley-git** [comment]
Pull request accepted!
