### ISSUE TITLE
TLS Bug

### ISSUE THREAD

**Issue by mgallagher01** [SRF-Consulting-Group-Inc/iris#4]
Doug has suggested some possible issues relating to an authenticaion/TLS handling bug in IRIS, but they don't seem to be the same as what we see.

We have a work around, but need to get a pull request to Doug to get this incorporated into IRIS.

Close this when there's a new IRIS release that fixes it.

**Comment by mgallagher01** [comment]
Version 1.3 will not authenticate to the IRIS server.  Currently forcing version 1.2 as a workaround.

**Comment by jlstanley-git** [comment]
Doug accepted the PR.
