### ISSUE TITLE
Support NDOT Gate Controller-Based Beacons

### ISSUE THREAD

**Issue by mgallagher01** [SRF-Consulting-Group-Inc/iris#47]
Scott Clinger (NDOT D5) hacked a gate controller to operate roadside beacons that are not directly associated with a road closure gate.  He added these to IRIS as a gate, which could be confusing for operators.

IRIS has a beacon device type, so this should be added as a supported beacon controller (Comm Link type) and the user interface should operate these like other beacons supported by IRIS.

Adding this was discussed with Matt Baker in May, 2022 and approved as a task.

Adding support will require a test device from NDOT, which Scott should be able to provide.

**Comment by jlstanley-git** [comment]
PR for this feature has been submitted to MNDOT.

**Comment by jlstanley-git** [comment]
PR was accepted Tuesday, Jan. 3rd.
