### ISSUE TITLE
Multi-gate status display bug

### ISSUE THREAD

**Issue by mgallagher01** [SRF-Consulting-Group-Inc/iris#5]
@jlstanley-git discovered during testing of "live" gates when there are several gates in an array connected to a single controller.
Fix is tested using gate simulator, but could still be tested using a live gate for completeness.

Close this when a patch is accepted by upstream/Doug.

**Comment by mgallagher01** [comment]
Waiting on accepting from upstream.

**Comment by jlstanley-git** [comment]
Closing this because the recent gate PR seems to have fixed this issue.
