### ISSUE TITLE
Gate Interlock Disable

### ISSUE THREAD

**Issue by mgallagher01** [SRF-Consulting-Group-Inc/iris#6]
Fix to allow roadway location & direction to be set for each gate without causing an interlock condition where all gates must have the same (open or closed) state.

Requires a mechanism to define a gate style (NDOT, MnDOT, etc.) and then apply or not interlock requirements.

Development started on mechanism.  Pull requests to be submitted in "bite size" chunks to upstream.

**Comment by mgallagher01** [comment]
Note that this is different from the "system disable" function of IRIS that disables all gate actions upon any configuration change to gates.  We currently deal with that using a script that automatically re-enables gates by "touch"-ing the appropriate file.

**Comment by jlstanley-git** [comment]
The recent gate PR accepted by Doug may have provided a work-around for this issue.  But we need to test it in an NDOT environment.

**Comment by mgallagher01** [comment]
Appears to be a feature in 5.32.0
